[{"ContainerToolsException.Message":"Failed to stop the application within the container. Build may fail because the files are in use. Docker command failed with exit code 126.","ContainerToolsException.ErrorCode":"CTP1006","ContainerToolsException.StackTrace":"   at Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<KillAppInsideContainerAsync>d__4.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildTask.<ExecuteAsync>d__26.MoveNext()","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: Docker command failed with exit code 126.\r\n   at Microsoft.VisualStudio.Containers.Tools.Common.Client.DockerClient.<ExecAsync>d__17.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<KillAppInsideContainerAsync>d__4.MoveNext()\r\nError code: CTC1029\r\nSeverity: Error\r\nCommand line: docker exec -i 689693c78eea07980901f0fa04fc9cda81c8a0e71b73906a9a9933b1594d7737 cmd /C \"IF EXIST C:\\remote_debugger\\x64\\utils\\KillProcess.exe C:\\remote_debugger\\x64\\utils\\KillProcess.exe dotnet.exe\"\r\nCommand exit code: 126\r\nCommand output: OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: \"cmd\": executable file not found in $PATH: unknown\r\nCommand error: \r\n"}]